# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
providers:
  - anthropic:messages:claude-3-5-sonnet-20241022

prompts:
  - file://prompt.json

tests:
  - vars:
      # base64 -i ~/card.png | pbcopy
      image: 'base64encodedpnghere'
    assert:
      - type: is-json
      - type: javascript
        value: |
          const result = JSON.parse(output);
          return (
            result.resourceType === 'Coverage'
          );
      - type: llm-rubric
        value: Returns John Example as the subscriber
      - type: llm-rubric
        value: Returns Anthem as the payer
      - type: llm-rubric
        value: Returns member id as 12345678
