# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'Extracting US Core Encounter Profile from clinical note'

providers:
  - anthropic:messages:claude-3-5-sonnet-20241022
  - openai:chat:gpt-4o
  - openai:chat:gpt-4o-mini

prompts:
  - file://./extract-unstructured-encounter-profile-first-experiment.json

tests:
  - vars:
      note: |
        Patient John Smith (DOB: 1990-01-15) presented with fever (39.2°C) and cough on 2024-03-15. 
        BP was 120/80. History of asthma. Prescribed azithromycin 500mg daily for 3 days.
    assert:
      - type: is-json
      - type: javascript
        value: |
          const result = JSON.parse(output);
          return (
            result.resourceType === 'Encounter'
          );
      - type: factuality
        value: |
          The response should only contain an Encounter FHIR resource.
