# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'FHIR Data Extraction Evaluation'

providers:
  - anthropic:messages:claude-3-5-sonnet-20241022
  - openai:chat:gpt-4o
  - openai:chat:gpt-4o-mini

prompts:
  - label: 'Clinical Note to FHIR'
    description: 'Extract structured FHIR-compliant data from clinical notes'
    raw: |
      You are a FHIR data extraction specialist. Extract structured FHIR-compliant data from the following clinical note.
      Output only valid FHIR JSON, with no additional explanation.

      Clinical Note:
      {{note}}

tests:
  - vars:
      note: |
        Patient John Smith (DOB: 1990-01-15) presented with fever (39.2°C) and cough on 2024-03-15. 
        BP was 120/80. History of asthma. Prescribed azithromycin 500mg daily for 3 days.
    assert:
      - type: is-json
      - type: javascript
        value: |
          const result = JSON.parse(output);
          return (
            result.resourceType === 'Bundle' &&
            result.type === 'collection' &&
            result.entry.some(e => e.resource.resourceType === 'Patient') &&
            result.entry.some(e => e.resource.resourceType === 'Observation') &&
            result.entry.some(e => e.resource.resourceType === 'MedicationRequest')
          );

  - vars:
      note: |
        Follow-up visit for Sarah Johnson on 2024-03-10.
        Patient reports improved diabetes control. A1C down to 6.8% from 7.5%.
        Continue metformin 1000mg BID.
    assert:
      - type: is-json
      - type: javascript
        value: |
          const result = JSON.parse(output);
          const hasA1c = result.entry.some(e => 
            e.resource.resourceType === 'Observation' &&
            e.resource.code?.coding?.some(c => c.code === '4548-4')
          );
          const hasMetformin = result.entry.some(e =>
            e.resource.resourceType === 'MedicationRequest' &&
            e.resource.medicationCodeableConcept?.coding?.some(c => 
              c.display?.toLowerCase().includes('metformin')
            )
          );
          return hasA1c && hasMetformin;
