# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'FHIR Validation using Tool Functions'

providers:
  - id: openai:chat:gpt-4o-mini
    config:
      tools:
        - type: function
          function:
            name: fhir_validate
            description: Validates a FHIR Resource
            input_schema:
              type: object
              properties:
                resource:
                  type: object
                  description: The FHIR Encounter resource to validate
              required:
                - resource

prompts:
  - label: 'FHIR Validator with Tools'
    description: 'Validate FHIR resources using available tool functions'
    raw: |
      You are a FHIR validation specialist with access to validation tools.
      Use the available functions to validate the FHIR resource and provide a summary of the results.

      FHIR Resource to validate:
      {{resource}}

tests:
  # Test basic validation with invalid resource
  - vars:
      resource: |
        {
          "resourceType": "Patient",
          "name": [
            {
              "use": "invalid",
              "family": "Smith"
            }
          ]
        }
    assert:
      - type: is-json
      - type: is-valid-openai-tools-call
      - type: javascript
        value: output[0].function.name === 'fhir_validate'

  # Test terminology validation
  - vars:
      resource: |
        {
          "resourceType": "Observation",
          "status": "final",
          "code": {
            "coding": [
              {
                "system": "http://loinc.org",
                "code": "8480-6",
                "display": "Systolic blood pressure"
              }
            ]
          },
          "valueQuantity": {
            "value": 120,
            "unit": "mmHg",
            "system": "http://unitsofmeasure.org",
            "code": "mm[Hg]"
          }
        }
    assert:
      - type: is-json
      - type: is-valid-openai-tools-call
      - type: javascript
        value: output[0].function.name === 'fhir_validate'

  # Test profile-based validation
  - vars:
      resource: |
        {
          "resourceType": "Patient",
          "meta": {
            "profile": [
              "http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient"
            ]
          },
          "name": [
            {
              "use": "official",
              "family": "Smith",
              "given": ["John"]
            }
          ],
          "gender": "male"
        }
    assert:
      - type: is-json
      - type: is-valid-openai-tools-call
      - type: javascript
        value: output[0].function.name === 'fhir_validate'
